version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: Etc/UTC
    commit-message:
      prefix: chore
      include: scope
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
